### PR TITLE
Add book modal

### PR DESCRIPTION
**Pull request by makeithappenmike**

### CODE REVIEW

**Review by isayani — CHANGES_REQUESTED** [review]
This looks great Mike! You just need to take out your testing route from homeRoutes and then PR again :)

**Review by isayani — CHANGES_REQUESTED** [review]
script.js has vars - let's change to const or let!

**Review by isayani — APPROVED** [review]
Approved - vars will be changed with next PR (if not already)

P.S. you are killing it Mike!

**Review by VaishaliQA — APPROVED** [review]
Approved

**Pull request merged**
