### PR TITLE
add DB schema and seeds

### PR DESCRIPTION
**Pull request by macgreene14**
Structured models and added seeds

### CODE REVIEW

**Review by VaishaliQA — CHANGES_REQUESTED** [review]
Please remove commented code from server.js file if you are not gonna use in future.
// ----- TEST ROUTE START
// ----- TEST ROUTE END

**Review by isayani — APPROVED** [review]
Looks good - will remove test routes when final routes are added.

**Review by VaishaliQA — APPROVED** [review]
Based on discussion, Insha will remove commented code once routes are added. 
Approving request.

**Comment by VaishaliQA** [comment]
Merged into main branch.

**Pull request merged**
